### ISSUE TITLE
que bom que voltou!

### ISSUE THREAD

**Issue by ratsclub** [lukkaslt/lukkaslt.github.io#1]
opa, estava tentando entrar em contato contigo, massa ver movimento na tua conta!

se puder, me chama no discord ratsclub#6724 :smiley:

**Comment by lukkaslt** [comment]
Enviado, meu caro. Mas quem é você? Não me recordo.

**Comment by lukkaslt** [comment]
> opa, estava tentando entrar em contato contigo, massa ver movimento na tua conta!
> 
> se puder, me chama no discord ratsclub#6724 😃

Enviado, meu caro. Mas quem é você? Não me recordo

**Comment by ratsclub** [comment]
Eu conversava bastante contigo (usava o nick de cap), não lembro se na Liga dos Programadores ou Fábrica de Noobs, mas você sumiu há uns 2 anos falando sobre sua caminhada no catolicismo e gostaria de saber como isso se desdobrou e como tu está atualmente! ;-)
